name: SPARQL Unicorn Ontology Documentation CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    with:
      version: v017
      rdffilepath: rdf/ogham/og_sites_1.ttl rdf/ogham/og_stones_1.ttl rdf/ogham/og_persons_1.ttl rdf/ogham/og_locations_1.ttl rdf/ogham/og_words_1.ttl rdf/ogham/og_inscriptions_1.ttl rdf/ogham/og_readings_1.ttl rdf/geodata/gs_ireland_island_1.ttl rdf/geodata/gs_provinces_1.ttl rdf/geodata/gs_baronies_1.ttl rdf/geodata/gs_baronies_2.ttl rdf/geodata/gs_baronies_3.ttl rdf/geodata/gs_baronies_4.ttl rdf/crosstable/ct_stone_site_1.ttl rdf/crosstable/ct_stone_word_1.ttl rdf/crosstable/ct_stone_person_1.ttl
      docpath: docs
      prefixns: http://lod.ogham.link/data/
      prefixnsshort: fsld
      indexpages: true
      createcollections: true
      createVOWL: true
      preferredlang: en
      ghpages: true
      metadatatable: true
      createnonNSPages: true
      logourl: https://raw.githubusercontent.com/LinkedOpenOgham/unicorn-ontdoc-template-ogham/main/icons/linkedopenogham_icon.png
      templatedir: https://github.com/LinkedOpenOgham/unicorn-ontdoc-template-ogham/archive/refs/tags/ogham.0.3.zip
      ogcapifeatures: false
      datasettitle: Linked Open Ogham
